name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: https://hub.docker.com/repository/docker/ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: build and test
        run: |
          rsync -av ./ /root/ROS2/ros2_ws/src/mypkg/
          cd /root/ROS2/ros2_ws
          rosdep update
          rosdep install -i --from-path src --rosdistro foxy -y
          bash -xv ./src/mypkg/test/test.bash /root
